import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import ashwani from "../public/ashwani.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ashwani Kumar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between ">
            <h1 className="text-2xl font-bold dark:text-white">eagerashwani</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-orange-700 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 font-medium text-orange-400 md:tect-6xl">
              Ashwani Kumar
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Engineer and Developer
            </h3>
            <p className=" text-sm leading-8 text-gray-800 dark:text-slate-100 md:text-xl max-w-xl mx-auto">
              By Profession, I'm a software engineer who like to develop
              websites with{" "}
              <span className="text-orange-600">latest tech stack</span> in the
              market.
            </p>
            <p className=" text-sm leading-8 text-gray-800 dark:text-slate-100 md:text-xl max-w-xl mx-auto">
              By Passion. I'm a{" "}
              <span className="text-orange-600">stock trader</span> who love to
              trade derivatives and holds equity.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://twitter.com/eagerashwani"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillTwitterCircle className="dark:text-slate-100" />
            </a>
            <a
              href="https://www.linkedin.com/in/eagerashwani/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin className="dark:text-slate-100" />
            </a>
            <a
              href="https://www.youtube.com/@eagerashwani/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillYoutube className="dark:text-slate-100" />
            </a>
          </div>
          <div className="relative shadow-gray-500 shadow-lg mx-auto bg-gradi from bg-orange-300 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:shadow-black">
            <Image
              src={ashwani}
              layout="fill"
              alt="ashwaniimage"
              objectFit="cover"
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-3 dark:text-slate-50">
              Projects I made
            </h3>
            <p className="text-md py-3 leading-8 text-gray-600 dark:text-slate-100">
              Checkout all my projects that I build in my <span className="text-orange-600">spare time. </span>Some 
              projects I was made in my college. You can also see the <span className="text-orange-600">source code</span> and <span className="text-orange-600">live demo</span> of every project, I ever made.             
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-md p-10 rounded-xl my-10 dark:bg-slate-900">
              <Image src={ashwani} alt="" height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-slate-50">
                Mess Smasher
              </h3>
              <p className="py-2 dark:text-slate-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
                temporibus sunt rerum, earum aspernatur suscipit!
              </p>
              <h4 className="py-4 text-orange-500">Tech stack I used</h4>
              <p className="text-gray-700 py-1 dark:text-slate-100">Node Js</p>
              <p className="text-gray-700 py-1 dark:text-slate-100">
                JavaScript
              </p>
            </div>
            <div className="text-center shadow-md p-10 rounded-xl my-10 dark:bg-slate-900">
              <Image src={ashwani} alt="" height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-slate-50">
                Mess Smasher
              </h3>
              <p className="py-2 dark:text-slate-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
                temporibus sunt rerum, earum aspernatur suscipit!
              </p>
              <h4 className="py-4 text-orange-500">Tech stack I used</h4>
              <p className="text-gray-700 py-1 dark:text-slate-100">Node Js</p>
              <p className="text-gray-700 py-1 dark:text-slate-100">
                JavaScript
              </p>
            </div>
            <div className="text-center shadow-md p-10 rounded-xl my-10 dark:bg-slate-900">
              <Image src={ashwani} alt="" height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-slate-50">
                Mess Smasher
              </h3>
              <p className="py-2 dark:text-slate-200">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
                temporibus sunt rerum, earum aspernatur suscipit!
              </p>
              <h4 className="py-4 text-orange-500">Tech stack I used</h4>
              <p className="text-gray-700 py-1 dark:text-slate-100">Node Js</p>
              <p className="text-gray-700 py-1 dark:text-slate-100">
                JavaScript
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-3 leading-8 text-gray-600 dark:text-slate-100">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ab
              magni <span className="text-orange-600">ratione</span>, possimus
              hic, blanditiis doloribus tenetur quia aspernatur accusamus
              perferendis. Velit, fuga debitis sed nemo ullam{" "}
              <span className="text-orange-600">laudantium</span> aliquid totam.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
